services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '$MONGODB_PORTS:27017'
    env_file: [.env, .env-mongo]
    environment:
      DATA_DIR: /data/db
    volumes:
      - mongodb:/data/db:rw
      - ./docker-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: mongod

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - $MONGO_EXPRESS_PORT:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_SERVER: 'mongo'
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongodb:
